### ISSUE TITLE
Write documentation on Fuse.Gestures.Swipe once it is released

### ISSUE THREAD

**Issue by petterroea** [fusetools/handbook-docs#58] opened 2015-12-17 18:14 UTC
The current trigger, `EdgeSwipeAnimation`, is being outphased. According to mortoray, it is being replaced by a trigger called `Swipe`.

Once it is released, we should mention it in the docs.

**Comment by sebbert** [comment] 2015-12-22 10:47
duplicate of #27

**Closed by sebbert** 2015-12-22 10:47 UTC
